### ISSUE TITLE
Numerical enum support (and some others)

### ISSUE THREAD

**Issue by macropygia** [astahmer/openapi-zod-client#49]
Hi,

In v1.4.5, numerical enums convert to a union of string literals.
However, Zod officially says that numerical enums should be a union of numeric literals. (ref: https://github.com/colinhacks/zod/issues/338)
And an unnecessary `.int()` is added if the type is an integer.

```yaml:OAS.yaml
openapi: 3.0.0
info:
  version: 1.0.0
  title: Numerical enums
paths:
  /sample:
    get:
      parameters:
        - in: query
          name: foo
          schema:
            type: integer
            enum:
              - 1
              - -2
              - 3
        - in: query
          name: bar
          schema:
            type: number
            enum:
              - 1.2
              - 34
              - -56.789
      responses:
        "200":
          description: resoponse
```

```ts:api.client.ts
parameters: [
    {
        name: "foo",
        type: "Query",
        schema: z
            .union([z.literal("1"), z.literal("-2"), z.literal("3")])
            .int() // should remove
            .optional(),
    },
    {
        name: "bar",
        type: "Query",
        schema: z.union([z.literal("1.2"), z.literal("34"), z.literal("-56.789")]).optional(),
    },
],
```

I expected as following:

```ts:api.client.ts
parameters: [
    {
        name: "foo",
        type: "Query",
        schema: z.union([z.literal(1), z.literal(-2), z.literal(3)]).optional(),
    },
    {
        name: "bar",
        type: "Query",
        schema: z.union([z.literal(1.2), z.literal(34), z.literal(-56.789)]).optional(),
    },
],
```

**Comment by astahmer** [comment]
hey, makes sense ! i'll look into it asap

**Comment by astahmer** [comment]
should be fixed & released in v1.4.6

**Comment by macropygia** [comment]
How fast.
I lost the chance to commit to the great OSS :yum:

BTW, I'm playing with some YAML in the playground and have found some more bugs in OAS to Zod converter.
Could I write here? Or create a new issue?

**Comment by astahmer** [comment]
haha I'm sure you will have your chance soon enough ! especially if you found more bugs 😁

yes of course, post it here if you want, it's fine

and thanks for the details on your original issue btw, it helped me solving it quickly 🙏

**Comment by macropygia** [comment]
Bugs can be reproduced with the following:

```yaml
openapi: 3.0.0
info:
  version: 1.0.0
  title: Schema Test
components:
  schemas:
    test1:
      type: object
      properties:
        text1:
          type: string
          pattern: "[^\u0000-\u001F\u007F]+"
    test2:
      type: object
      properties:
        text2:
          type: string
          minLength: 5
          maxLength: 10
    test3:
      type: object
      properties:
        text3:
          type: string
    test4:
      allOf:
        - $ref: "#/components/schemas/test1"
        - $ref: "#/components/schemas/test2"
        - $ref: "#/components/schemas/test3"
```

## Control characters print directly

Control characters are sometimes used in regexp to ban themselves.

```ts
const test1 = z.object({ text1: z.string().regex(/[^█-██]+/) }).partial();
```

https://github.com/astahmer/openapi-zod-client/blob/d4ae7d10263bd58aea61dcf80d2c9db61d2dfdd4/lib/src/openApiToZod.ts#L248-L250

## `minLength` and `maxLength` parse incorrectly for string

```ts
const test2 = z.object({ text2: z.string().length(5) }).partial();

// Expect:
const test2 = z.object({ text2: z.string().min(5).max(10) }).partial();
```

https://github.com/astahmer/openapi-zod-client/blob/d4ae7d10263bd58aea61dcf80d2c9db61d2dfdd4/lib/src/openApiToZod.ts#L240-L246

## Missing `.`

```ts
const test4 = test1.and(test2)and(test3);
```

https://github.com/astahmer/openapi-zod-client/blob/d4ae7d10263bd58aea61dcf80d2c9db61d2dfdd4/lib/src/openApiToZod.ts#L94-L97

**Comment by astahmer** [comment]
ok got it ! will probably look into it tomorrow

**Comment by astahmer** [comment]
### Control characters print directly

so just to be sure, the expected output would be this, right ?

```ts
const test1 = z.object({ text1: z.string().regex(/[^\u0000-\u001F\u007F]+/) }).partial();
```

### minLength and maxLength parse incorrectly for string

oh ok my bad, I interpreted it as min&max should be "===", but you actually just want a range 😅 , will fix !

### Missing .

looking into it !

**Comment by macropygia** [comment]
> the expected output would be this, right ?

Yes.

> have you any idea ?

oh...
I think that is no problem in practical use with either `\u0001` or `\x01`.
It's good if they are escaped for now.

![image](https://user-images.githubusercontent.com/3162324/206919172-b2818da2-c454-4ce1-95be-3f5d1cfa35ae.png)

**Comment by astahmer** [comment]
https://github.com/astahmer/openapi-zod-client/commit/d394d86059484b32c39bd91aa1897d2373c3d373
https://github.com/astahmer/openapi-zod-client/commit/fb2fc0ce838414d652db4c7fc3e812339dd3a685

the regex one remains, maybe you want to take care of it ?

**Comment by macropygia** [comment]
> you want to take care of it ?

I’ll look into it.

---

Another one.

```yaml
openapi: 3.0.0
info:
  title: Schema test
  version: 1.0.0
components:
  schemas:
    test1:
      type: string
      minLength: 5
    test2:
      type: integer
      minimum: 10
    test3:
      required:
        - text
        - num
      properties:
        text:
          type: string
          minLength: 5
        num:
          type: integer
          minimum: 10
```

```ts
const test1 = z.string();
const test2 = z.number();
const test3 = z.object({ text: z.string().min(5), num: z.number().int().gte(10) });
```

Is `getZodChain` malfunctioning with non-object schemas in components?

**Comment by astahmer** [comment]
getZodChain must be called explicitly when needed, this was not the case until now
I purposely didn't append zod chains for the body/response cause I expected it would always be a `z.object`

[I pushed a PR](https://github.com/astahmer/openapi-zod-client/pull/51) for those missing chains, can you confirm this is what you need ? if not, could you add some more tests or even try to fix it ? it should be similar to that commit I just made

**Comment by macropygia** [comment]
> I purposely didn't append zod chains for the body/response cause I expected it would always be a z.object

Sorry for the lack of explanation.
I assumed that a component that is not an object would be used as part of an object.

Like this:

```yaml
openapi: 3.0.0
info:
  title: Schema test
  version: 1.0.0
paths:
  /user/add:
    post:
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/AddUser"
      responses:
        "200":
          description: foo
  /user/recover:
    post:
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/PasswordReminder"
      responses:
        "200":
          description: bar
components:
  schemas:
    Password:
      type: string
      pattern: /(PasswordRegex)/
      minLength: 16
      maxLength: 255
    Email:
      type: string
      pattern: /(EmailRegex)/
      minLength: 6
      maxLength: 255
    AddUser:
      required:
        - email
        - password
      properties:
        email:
          $ref: "#/components/schemas/Email"
        password:
          $ref: "#/components/schemas/Password"
    PasswordReminder:
      required:
        - email
      properties:
        email:
          $ref: "#/components/schemas/Email"
```

**Comment by astahmer** [comment]
okay, so since I misunderstood the problem & solved another [in this PR](https://github.com/astahmer/openapi-zod-client/pull/51), I'll leave this one open since it might not be needed

as for the actual problem you noticed, refs props in z.object missing their zod chains methods, it should be fixed in [this new PR](https://github.com/astahmer/openapi-zod-client/pull/55)

[is it ok now ?](https://openapi-zod-client-git-fix-missing-zod-chains-o-f2c458-astahmer.vercel.app/?doc=PYBwpgdghiCWBcACAzAOgAwYFCwgM2Hi0UQBdZSAbMJAZQGMALMAWyjLAGdTjEA3MACdOsYBCQBGDNhBRSjTkRIB6AK6chyqABNtSkohDBu%2Bg4kFgAjqq6kAQsG0BPU2fNXVsC3rKCbvN0R6MVJIUldAmBBKWHo5UQhlACtOMQjAxE4mVih0jMQAEgs8JAAiAGJlYJYjCDDOZSzmNgaAQV0AVQ1BUoCDC05ajUU%2Bs1KAJnR0UryDbS56QVgQcjTEAmBeNW7lC2CBQVcjE1H3a1sHZ1mLay8wH1I-MFOSYIhQ99mSKJi41cSUmkXm4mjkvm4imASogKlVgDUxPVGtkWsoAApQTicADuwEE2gASqxcPMeqcBkMuLMJlMZsCSPMsksVgkkAAjKCCLDVWr1fSglquDFY3H49KkJzgJDcJYQADmp1kpFCgnEiGUAAphTi8YSwHKwAAPACUylOLFwABlIHL5JIAGzmqCG63yu2IcYAVk9fQAomxYJRxZKaJlHrgFYElSq1Zr-VBA0SDSazYELRBXbbGEhHWnnZn3V6fWZ2toukJ0jdPN5ZgBaRA5QPA%2BuyEW6xWCUBCchU4GNoP0wrFMqVHmI94NAWY5TxwO9fKtnViweQ6Gwsd1CfI5rT7Wi7Tzgx73VE9OkyseO56ZsNgOUDtdwQ9kb5fvg1cjuEIzekSco6ezpQpRAA)

**Comment by macropygia** [comment]
It works however I expected the lower one. 
Which is better?

```ts
const Email = z.string();
const Password = z.string();
const AddUser = z.object({
  email: Email.min(6)
    .max(255)
    .regex(/(EmailRegex)/),
  password: Password.min(16)
    .max(255)
    .regex(/(PasswordRegex)/),
});
const PasswordReminder = z.object({
  email: Email.min(6)
    .max(255)
    .regex(/(EmailRegex)/),
});
```

```ts
const Email = z.string().min(6).max(255).regex(/(EmailRegex)/);
const Password = z.string().min(16).max(255).regex(/(PasswordRegex)/);
const AddUser = z.object({
  email: Email,
  password: Password,
});
const PasswordReminder = z.object({
  email: Email,
});
```

I'm trying to add `getZodChain(schema, { isRequired: true })` after these `getZodSchema`. (based on v1.4.13)

https://github.com/astahmer/openapi-zod-client/blob/9a5d3e62637c2d565a56c30fb0b4c5819bd32447/lib/src/openApiToZod.ts#L54

https://github.com/astahmer/openapi-zod-client/blob/9a5d3e62637c2d565a56c30fb0b4c5819bd32447/lib/src/template-context.ts#L36

**Comment by astahmer** [comment]
the upper one was made so that the schemas could be re-used across paths/components while having different chains

example:
```ts
const Thing = z.object(...);
const ListOfThings = z.array(Thing);

const endpoints = makeApi([
	{
		method: "xx",
		path: "xx",
		response: Thing.partial()
	},
	{
		method: "yy",
		path: "yy",
		response: ListOfThings
	},
]
```

whereas if you use the lower one you'll tie the schemas with the chains and then might end-up having to duplicate the schemas under another name just cause the chains are different

example:
```ts
const Thing = z.object(...).partial();
const ListOfThings = z.array(z.object(...));

const endpoints = makeApi([
	{
		method: "xx",
		path: "xx",
		response: Thing
	},
	{
		method: "yy",
		path: "yy",
		response: ListOfThings
	},
]
```

another option could be to have a mix of both, like:

```ts
const Thing = z.object(...);
const PartialThing = Thing.partial()
const ListOfThings = z.array(Thing);

const endpoints = makeApi([
	{
		method: "xx",
		path: "xx",
		response: PartialThing
	},
	{
		method: "yy",
		path: "yy",
		response: ListOfThings
	},
]
```

**Comment by astahmer** [comment]
![Screenshot 2022-12-12 at 22 52 53](https://user-images.githubusercontent.com/47224540/207163043-c1f8489b-c8c5-4e48-977e-02c0f1131f36.png)


this is more or less what this option (`complexityThreshold`) is for, you can get the lower result with this

you can play with it in the playground and see how it reacts in the output (you need to save each time you want to apply the changes)

**Comment by macropygia** [comment]
I understood.

I was uncomfortable with no one-to-one mapping between components on OAS and variables on TS including conditions.
If convenience is a priority, this is not a matter.
(And I didn't know until just now that it was possible to override the props of $ref with sibling elements from OpenAPI 3.1. Swagger still does not support...)

So, now I can convert 6k+ lines of YAML on the current project and save a lot of time :beer:

**Comment by astahmer** [comment]
glad to hear that 🙏 

is everything addressed in this issue and if yes, can we close it ?

**Comment by macropygia** [comment]
Yes, completed.
Great thanks.
